// test-report-writer.unit.test.ts — plan 07a41ec6 T5（openspec efficiency-first-closure
// 「The testing report is generated by the harness and concludes per axis」）
//
// 钉住：生成的报告能被既有解析器逐格读回、与 timing/trace 对账零失配、结论按轴确定性派生
// （功能 FAIL → 不达标；有 gap/视觉未验 → 有条件达标）、缺陷表由失败 StepResult 机器填、
// 首次覆盖手写报告时旧文迁到 testing/notes.legacy-report.md。

import assert from 'assert';
import * as fs from 'fs';
import * as os from 'os';
import * as path from 'path';

import { clearFrameworkConfigCache, featurePhaseReportsDir, resolveFeatureArtifact } from '../../config';
import { evaluateExecutionChannelDeclaration } from '../../scripts/utils/execution-channel';
import { classifyPhaseAssessment } from '../../scripts/utils/phase-transition-policy';
import {
  parseReportConclusionVerdict,
  parseReportExecutionRows,
  reconcileReportWithDeviceTestTiming,
  reconcileReportWithHylyreTrace,
} from '../../scripts/utils/testing-trace-gates';
import {
  TEST_REPORT_GENERATED_MARKER,
  generateTestReport,
  writeGeneratedTestReport,
} from '../../../profiles/hmos-app/harness/test-report-writer';
import type { UnitCaseResult } from '../run-unit';

const FEATURE = 'rw-fixture';
const PLAN_MD = [
  '# 测试计划',
  '',
  '## 三、测试用例清单',
  '',
  '| 用例编号 | 用例名称 | 前置条件 | 测试步骤 | 预期结果 | 优先级 | 关联 AC | 执行通道 |',
  '| --- | --- | --- | --- | --- | --- | --- | --- |',
  '| TC-001 | 打开卡包 | 首页 | 点卡包 | 进入卡包 | P0 | AC-1 | hylyre |',
  '| TC-002 | 添加卡片 | 卡包 | 点添加 | 进入添加页 | P1 | AC-2 | hylyre |',
  '| TC-003 | 帧率 | 卡包 | 滑动 | ≥54FPS | P1 | AC-3 | manual:perf_sampling |',
  '',
].join('\n');

function mkProject(): string {
  const root = fs.mkdtempSync(path.join(os.tmpdir(), 'maison-report-writer-'));
  clearFrameworkConfigCache();
  return root;
}

function writeJson(p: string, v: unknown): void {
  fs.mkdirSync(path.dirname(p), { recursive: true });
  fs.writeFileSync(p, JSON.stringify(v, null, 2), 'utf-8');
}

function step(index: number, kind: string, role: 'action' | 'assertion', passed: boolean, id: string) {
  return {
    index, kind, role, duration_ms: 100, device_session: null, artifacts: [], diagnostic: passed ? null : 'element not found within 10s', extensions: {},
    outcome: passed
      ? (role === 'assertion' ? { status: 'passed', observation: { kind: 'assertion', assertion_type: 'presence', facts: { observed_present: true, candidate_count: 1 } } } : { status: 'passed' })
      : { status: 'failed', failure: { domain: 'assertion', code: 'assertion.mismatch', message: `${id} 未出现` } },
    selector: { request: { kind: 'by_id', value: id }, resolution: { state: passed ? 'unique' : 'not_found', candidate_count: passed ? 1 : 0, selected: passed ? { id } : null, candidates: [] } },
  };
}

function seed(root: string, opts: { tc002Failed?: boolean } = {}): { reportsDir: string; tracePath: string; timing: unknown } {
  const reportsDir = featurePhaseReportsDir(root, FEATURE, 'testing');
  const runDir = path.join(reportsDir, '20260903-000000', 'hylyre');
  const tracePath = path.join(runDir, 'trace.json');
  const c2Passed = !opts.tc002Failed;
  writeJson(tracePath, {
    schema_version: '0.4-p0', result_protocol: 'hylyre.step-outcome/1', feature: FEATURE, phase: 'testing',
    outcome: c2Passed ? 'success' : 'failed',
    cases: [
      { id: 'TC-001', name: '打开卡包', status: '通过', priority: 'P0', ac_ref: 'AC-1', notes: '', execution: 'completed', verification: 'passed', evidence: 'complete', expected_check_mode: 'empty',
        steps: [step(0, 'touch', 'action', true, 'home_card_pack'), step(1, 'wait_for', 'assertion', true, 'card_pack_title')] },
      { id: 'TC-002', name: '添加卡片', status: c2Passed ? '通过' : '失败', priority: 'P1', ac_ref: 'AC-2', notes: '', execution: 'completed', verification: c2Passed ? 'passed' : 'failed', evidence: 'complete', expected_check_mode: 'empty',
        steps: [step(0, 'touch', 'action', true, 'add_card_btn'), step(1, 'wait_for', 'assertion', c2Passed, 'add_card_title')] },
    ],
  });
  fs.writeFileSync(path.join(runDir, 'test-plan.hylyre.md'), '# 派生\n', 'utf-8');
  const timing = {
    schema_version: '1.0', feature: FEATURE, generated_at: '2026-09-03T00:02:00.000Z',
    pipeline: { build_ms: 1000, build_reused: false, install_ms: 0, install_reused: true, hylyre_run_ms: 5000, page_save_ms: 100, total_harness_ms: null, hap_built_at: '2026-09-03T00:00:00.000Z' },
    cases: [{ id: 'TC-001', duration_ms: 1234, step_count: 2 }, { id: 'TC-002', duration_ms: 2345, step_count: 2 }],
  };
  writeJson(path.join(reportsDir, 'device-test-timing.json'), timing);
  writeJson(path.join(reportsDir, 'device-test-build.result.json'), { timestamp: '2026-09-03T00:01:00.000Z', hapBuiltAt: '2026-09-03T00:00:00.000Z', reused: false });
  writeJson(path.join(reportsDir, 'device-test-run.meta.json'), { command: 'hylyre run --plan test-plan.hylyre.md', run_started_at: '2026-09-03T00:01:30.000Z', run_ended_at: '2026-09-03T00:01:40.000Z' });
  return { reportsDir, tracePath, timing };
}

function input(root: string, seeded: ReturnType<typeof seed>, overrides: Record<string, unknown> = {}) {
  return {
    projectRoot: root, feature: FEATURE, reportsDir: seeded.reportsDir, tracePath: seeded.tracePath, planMd: PLAN_MD,
    channelDecl: evaluateExecutionChannelDeclaration(PLAN_MD),
    now: () => new Date('2026-09-03T00:03:00.000Z'),
    ...overrides,
  };
}

const cases: Array<{ name: string; run: () => void }> = [
  {
    name: '全过 + 1 条 gap：既有解析器逐格读回，timing/trace 对账零失配，结论有条件达标（gap 与稳定性 UNKNOWN 披露）',
    run: () => {
      const root = mkProject();
      try {
        const seeded = seed(root);
        const gen = generateTestReport(input(root, seeded));
        const md = gen.content;
        assert.ok(md.startsWith(TEST_REPORT_GENERATED_MARKER), '生成标记');
        for (const h of ['## 一、测试概览', '### 真机流水线耗时', '## 二、测试执行结果', '## 三、缺陷清单', '## 四、通过率统计', '## 五、结论']) {
          assert.ok(md.includes(h), `缺章节 ${h}`);
        }
        const rows = parseReportExecutionRows(md);
        assert.deepStrictEqual(rows.map(r => [r.id, r.status, r.durationMs]), [['TC-001', '通过', 1234], ['TC-002', '通过', 2345], ['TC-003', '跳过', null]]);
        assert.ok(rows[2].durationRaw === '—', 'gap 行耗时占位');
        const timing = reconcileReportWithDeviceTestTiming(md, { timing: seeded.timing as never, buildTimestamp: '2026-09-03T00:01:00.000Z', hylyreTcIds: ['TC-001', 'TC-002'] });
        assert.deepStrictEqual(timing.mismatches, [], 'timing 对账零失配');
        const trace = reconcileReportWithHylyreTrace(md, seeded.tracePath, { hylyreTcIds: ['TC-001', 'TC-002'] });
        assert.deepStrictEqual(trace.mismatches, [], 'trace 对账零失配');
        assert.strictEqual(parseReportConclusionVerdict(md), '有条件达标');
        assert.strictEqual(gen.conclusion.functional, 'PASS');
        assert.strictEqual(gen.conclusion.visual_geometry, 'NOT_APPLICABLE', '无视觉面时视觉轴不适用、不进缺口');
        assert.strictEqual(gen.conclusion.overall, 'COMPLETE_WITH_GAPS');
        assert.ok(gen.conclusion.gaps.some(g => g.includes('TC-003[manual:perf_sampling]')), 'gap 披露');
        assert.ok(/unsupported_gap:perf_sampling/.test(md), '执行表备注写明 gap');
        assert.ok(/\| P0 \| 1 \| 1 \|/.test(md) && /\| P1 \| 2 \| 1 \|/.test(md), '通过率表按优先级：gap 留分母');
        assert.ok(/无缺陷/.test(md));
        assert.ok(/reused=false/.test(md) && /reused=true/.test(md), '流水线表带 reused 标记');
      } finally {
        fs.rmSync(root, { recursive: true, force: true });
      }
    },
  },
  {
    name: 'TC-002 失败：功能 FAIL → 不达标；缺陷表由失败 StepResult 机器填并关联用例；trace 对账仍零失配',
    run: () => {
      const root = mkProject();
      try {
        const seeded = seed(root, { tc002Failed: true });
        const gen = generateTestReport(input(root, seeded));
        const md = gen.content;
        assert.strictEqual(gen.conclusion.functional, 'FAIL');
        assert.strictEqual(gen.conclusion.overall, 'FAILED');
        assert.strictEqual(parseReportConclusionVerdict(md), '不达标');
        assert.ok(/\| DEF-001 \| TC-002 \| MAJOR \| 失败：step 1（wait_for） assertion\/assertion\.mismatch：add_card_title 未出现/.test(md), md.split('\n').filter(l => l.startsWith('| DEF')).join('\n'));
        const rows = parseReportExecutionRows(md);
        assert.strictEqual(rows.find(r => r.id === 'TC-002')?.status, '失败');
        const trace = reconcileReportWithHylyreTrace(md, seeded.tracePath, { hylyreTcIds: ['TC-001', 'TC-002'] });
        assert.deepStrictEqual(trace.mismatches, []);
        assert.ok(/\| MAJOR \| 1 \| 1 \|/.test(md), '缺陷统计');
      } finally {
        fs.rmSync(root, { recursive: true, force: true });
      }
    },
  },
  {
    name: '弱化旗标在场：报告披露旗标、区分执行完成与验收通过，且结论不为达标',
    run: () => {
      const root = mkProject();
      try {
        const seeded = seed(root);
        writeJson(path.join(seeded.reportsDir, 'device-test-run.meta.json'), { command: 'hylyre run --plan x --skip-assert-expected' });
        const gen = generateTestReport(input(root, seeded));
        assert.ok(gen.content.includes('--skip-assert-expected'), '披露旗标');
        assert.ok(/执行完成/.test(gen.content) && /非验收通过/.test(gen.content), '区分口径');
        assert.notStrictEqual(parseReportConclusionVerdict(gen.content), '达标');
      } finally {
        fs.rmSync(root, { recursive: true, force: true });
      }
    },
  },
  {
    name: 'P1 hylyre 未进 trace：保留 absent 兜底，functional/overall 均 FAIL',
    run: () => {
      const root = mkProject();
      try {
        const seeded = seed(root);
        const trace = JSON.parse(fs.readFileSync(seeded.tracePath, 'utf-8')) as Record<string, any>;
        trace.cases = trace.cases.filter((row: { id: string }) => row.id !== 'TC-002');
        trace.outcome = 'success';
        writeJson(seeded.tracePath, trace);
        const generated = generateTestReport(input(root, seeded));
        assert.strictEqual(parseReportExecutionRows(generated.content).find(row => row.id === 'TC-002')?.status, '跳过');
        assert.strictEqual(generated.conclusion.functional, 'FAIL');
        assert.strictEqual(generated.conclusion.overall, 'FAILED');
      } finally {
        fs.rmSync(root, { recursive: true, force: true });
      }
    },
  },
  {
    name: '组合链：6 Hylyre + visual P0 binding 贯通 report/assess；visual failed 同向阻断',
    run: () => {
      const root = mkProject();
      try {
        const seeded = seed(root);
        const nativeRows = Array.from({ length: 6 }, (_, i) => {
          const id = `TC-${String(i + 1).padStart(3, '0')}`;
          return `| ${id} | native ${i + 1} | 首页 | 执行 | 通过 | P0 | AC-1 | hylyre |`;
        });
        const visualPlan = [
          '# 测试计划', '', '## 测试用例、测试用例清单', '',
          '| 用例编号 | 用例名称 | 前置条件 | 测试步骤 | 预期结果 | 优先级 | 关联 AC | 执行通道 |',
          '| --- | --- | --- | --- | --- | --- | --- | --- |',
          ...nativeRows,
          '| TC-007 | 四屏视觉 | 最新构建 | 视觉检查 | 通过 | P0 | AC-8 | visual |', '',
        ].join('\n');
        const trace = JSON.parse(fs.readFileSync(seeded.tracePath, 'utf-8')) as Record<string, any>;
        const baseCase = trace.cases[0];
        trace.cases = Array.from({ length: 6 }, (_, i) => ({
          ...JSON.parse(JSON.stringify(baseCase)), id: `TC-${String(i + 1).padStart(3, '0')}`,
        }));
        writeJson(seeded.tracePath, trace);
        const timingPath = path.join(seeded.reportsDir, 'device-test-timing.json');
        const timing = JSON.parse(fs.readFileSync(timingPath, 'utf-8')) as Record<string, any>;
        timing.cases = Array.from({ length: 6 }, (_, i) => ({ id: `TC-${String(i + 1).padStart(3, '0')}`, duration_ms: 100 + i, step_count: 2 }));
        writeJson(timingPath, timing);
        const channelDecl = evaluateExecutionChannelDeclaration(visualPlan);
        const covered = generateTestReport(input(root, seeded, {
          planMd: visualPlan,
          channelDecl,
          channelEvidenceBindings: [{ tc_id: 'TC-007', channel: 'visual', verdict: { kind: 'covered', detail: 'AC-8 两个 canonical overlay/screens 证据通过（phase 四屏门 PASS）' } }],
        }));
        assert.strictEqual(parseReportExecutionRows(covered.content).filter(r => r.status === '通过').length, 7);
        assert.ok(/\| P0 \| 7 \| 7 \| 0 \| 0 \| 0 \| 100%/.test(covered.content), covered.content);
        assert.strictEqual(covered.conclusion.functional, 'PASS');
        assert.strictEqual(classifyPhaseAssessment({ verdict: 'PASS', phase: 'testing', retries_used: 0, max_retries_per_phase: 2 }).runner_action, 'advance');

        const failed = generateTestReport(input(root, seeded, {
          planMd: visualPlan,
          channelDecl,
          channelEvidenceBindings: [{ tc_id: 'TC-007', channel: 'visual', verdict: { kind: 'failed', detail: 'overlay 截图 build 已过期' } }],
        }));
        assert.strictEqual(parseReportExecutionRows(failed.content).find(r => r.id === 'TC-007')?.status, '失败');
        assert.strictEqual(failed.conclusion.functional, 'FAIL');
        assert.strictEqual(failed.conclusion.overall, 'FAILED');
        assert.ok(/\| DEF-\d+ \| TC-007 \| BLOCKER \| 失败：visual 通道：overlay 截图 build 已过期/.test(failed.content));
        assert.strictEqual(classifyPhaseAssessment({ verdict: 'FAIL', phase: 'testing', failure_kind: 'code_regression', retries_used: 0, max_retries_per_phase: 2 }).runner_action, 'retry');
      } finally {
        fs.rmSync(root, { recursive: true, force: true });
      }
    },
  },
  {
    name: '写盘：首次覆盖手写报告 → 旧文迁 testing/notes.legacy-report.md；再次生成不重复迁移',
    run: () => {
      const root = mkProject();
      try {
        const seeded = seed(root);
        const target = resolveFeatureArtifact(root, FEATURE, 'test-report.md').canonicalPath;
        fs.mkdirSync(path.dirname(target), { recursive: true });
        fs.writeFileSync(target, '# 手写报告\n\n代理写的分析。\n', 'utf-8');
        const first = writeGeneratedTestReport(input(root, seeded));
        assert.ok(first.written && first.legacy_moved_to, '首次应迁档');
        assert.ok(fs.readFileSync(first.legacy_moved_to!, 'utf-8').includes('代理写的分析'), '旧内容保留');
        assert.ok(fs.readFileSync(target, 'utf-8').startsWith(TEST_REPORT_GENERATED_MARKER), '新文件带生成标记');
        const second = writeGeneratedTestReport(input(root, seeded));
        assert.ok(second.written && !second.legacy_moved_to, '第二次不再迁档（已是机器报告）');
        assert.ok(fs.readFileSync(first.legacy_moved_to!, 'utf-8').includes('代理写的分析'), '迁档文件不被覆盖');
      } finally {
        fs.rmSync(root, { recursive: true, force: true });
      }
    },
  },
];

export function runAll(): UnitCaseResult[] {
  const results: UnitCaseResult[] = [];
  for (const c of cases) {
    try {
      c.run();
      results.push({ name: c.name, ok: true });
    } catch (err) {
      results.push({ name: c.name, ok: false, error: (err as Error).stack ?? (err as Error).message });
    }
  }
  return results;
}
