// ============================================================================
// test-report-writer.ts — 顶层 test-report.md 整份机器生成（plan 07a41ec6 T5 /
// openspec efficiency-first-closure「The testing report is generated by the harness and concludes per axis」）
// ----------------------------------------------------------------------------
// 宿主 2026-09-02 回归：11 个代理错误里 8 个是派生值失效（耗时取错字段、报告绑到被取代的 run、
// 流水线表缺失、统计表对不上），且为了对齐报告与 run 多跑了 4 轮真机。报告里每一格都来自
// trace / timing / meta / visual-diff / visual-debt / gaps，harness 已有解析它们的门禁
// （testing-trace-gates.ts），只差 writer——本模块就是那个 writer。
//
// 契约：
//   · 输出必须能被既有解析器逐格读回（parseReportExecutionRows / reconcileReportWithDeviceTestTiming /
//     parseReportConclusionVerdict / defect_table_format / pass_rate_calculated / visual_debt_disclosure）；
//   · 结论按轴确定性派生（功能 / 交互稳定性 / 视觉几何 / 视觉内容 / 视觉样式 / 已知缺口 / 总体）；
//     视觉不完整不阻止功能完成，但报告不得只看 trace 就宣称 UX 达标；
//   · agent 的观察写 testing/notes.md（不进门禁、closure、subject、freshness）；
//     首次覆盖旧的手写报告时，把它迁到 testing/notes.legacy-report.md 留档。
// ============================================================================

import * as fs from 'fs';
import * as path from 'path';
import * as crypto from 'crypto';
import { featureDir, resolveFeatureArtifact } from '../../../harness/config';
import { extractTables, getSectionContent } from '../../../harness/scripts/utils/markdown-parser';
import {
  isP0DeviceInteractive,
  loadAcceptanceFlowsDoc,
  parsePlanTcEntries,
} from '../../../harness/scripts/utils/p0-semantic-gates';
import type { ExecutionChannelDeclarationResult } from '../../../harness/scripts/utils/execution-channel';
import { countBlockingDebt, loadVisualDebtEx } from '../../../harness/scripts/utils/visual-debt';
import { parseHylyreTrace, type HylyreTrace, type HylyreTraceCase } from './providers/device-test-run';
import type { DeviceTestTimingDocument } from './device-test-timings';
import { validateVisualDiffJson } from './visual-diff-check';

export const TEST_REPORT_GENERATED_MARKER = '<!-- maison:generated:test-report v1 -->';

export interface TestReportWriterInput {
  projectRoot: string;
  feature: string;
  /** testing 阶段 reports 目录（device-test-*.meta.json / device-test-timing.json 所在） */
  reportsDir: string;
  /** 权威 run 的 hylyre/trace.json；null = 无本轮 trace（报告仍生成，功能轴 UNKNOWN） */
  tracePath: string | null;
  /** 顶层 test-plan.md 全文 */
  planMd: string;
  channelDecl: ExecutionChannelDeclarationResult;
  now?: () => Date;
}

export type AxisStatus = 'PASS' | 'FAIL' | 'UNKNOWN' | 'NOT_APPLICABLE';
export type CheckStatus = 'CHECKED' | 'UNKNOWN' | 'NOT_APPLICABLE';
export type OverallStatus = 'COMPLETE' | 'COMPLETE_WITH_GAPS' | 'FAILED';

export interface TestReportConclusion {
  functional: AxisStatus;
  stability: AxisStatus;
  visual_geometry: AxisStatus;
  visual_content: CheckStatus;
  visual_style: CheckStatus;
  gaps: string[];
  overall: OverallStatus;
  /** 报告声明行（达标 / 有条件达标 / 不达标） */
  declared_verdict: '达标' | '有条件达标' | '不达标';
}

export interface GeneratedTestReport {
  content: string;
  conclusion: TestReportConclusion;
  trace_path: string | null;
}

interface PlanRow {
  id: string;
  name: string;
  priority: string;
  channelRaw: string;
  acRefs: string[];
}

type RowStatus = '通过' | '失败' | '阻塞' | '跳过';

interface ExecRow {
  id: string;
  name: string;
  priority: string;
  status: RowStatus;
  duration: string;
  note: string;
  /** 参与"通过率"分子的执行事实来源 */
  source: 'hylyre' | 'visual' | 'gap' | 'invalid' | 'absent';
}

interface DefectRow {
  id: string;
  cases: string;
  severity: 'BLOCKER' | 'MAJOR' | 'MINOR';
  description: string;
  status: string;
}

function readJson<T>(p: string): T | null {
  try {
    if (!fs.existsSync(p)) return null;
    return JSON.parse(fs.readFileSync(p, 'utf-8')) as T;
  } catch {
    return null;
  }
}

function sha256File(p: string): string | null {
  try {
    return crypto.createHash('sha256').update(fs.readFileSync(p)).digest('hex');
  } catch {
    return null;
  }
}

function pickColumnIndex(headers: string[], keywords: string[]): number {
  for (const kw of keywords) {
    const idx = headers.findIndex(h => h.toLowerCase().includes(kw.toLowerCase()));
    if (idx >= 0) return idx;
  }
  return -1;
}

function parsePlanRows(planMd: string): PlanRow[] {
  const section = getSectionContent(planMd, '测试用例') ?? getSectionContent(planMd, '测试用例清单') ?? '';
  const tables = extractTables(section || planMd);
  const acByTc = new Map(parsePlanTcEntries(planMd).map(e => [e.id, e.acRefs]));
  if (tables.length === 0) return [];
  const t = tables[0];
  const iId = pickColumnIndex(t.headers, ['用例编号', '编号']);
  const iName = pickColumnIndex(t.headers, ['用例名称', '名称']);
  const iPri = pickColumnIndex(t.headers, ['优先级']);
  const iCh = pickColumnIndex(t.headers, ['执行通道', 'execution_channel', 'execution channel']);
  const out: PlanRow[] = [];
  const seen = new Set<string>();
  for (const row of t.rows) {
    const m = (iId >= 0 ? row[iId] : row[0] || '').match(/TC-\d+/i);
    if (!m) continue;
    const id = m[0].toUpperCase();
    if (seen.has(id)) continue;
    seen.add(id);
    out.push({
      id,
      name: (iName >= 0 ? row[iName] : '').trim(),
      priority: (iPri >= 0 ? row[iPri] : '').trim().toUpperCase() || 'P2',
      channelRaw: (iCh >= 0 ? row[iCh] : '').trim(),
      acRefs: acByTc.get(id) ?? [],
    });
  }
  return out;
}

function cell(v: string): string {
  return v.replace(/\|/g, '\\|').replace(/\r?\n/g, ' ');
}

function ms(v: number | null | undefined): string {
  return typeof v === 'number' && Number.isFinite(v) ? `${Math.round(v)}ms` : '—';
}

function firstFailedStepSummary(tc: HylyreTraceCase): string {
  const steps = Array.isArray(tc.steps) ? tc.steps : [];
  for (const step of steps) {
    const s = step as unknown as {
      index?: number; kind?: string; outcome?: { status?: string; failure?: { domain?: string; code?: string; message?: string } };
      diagnostic?: string | null;
    };
    if (!s || s.outcome?.status === 'passed' || s.outcome?.status === undefined) continue;
    const f = s.outcome?.failure;
    const where = `step ${s.index ?? '?'}（${s.kind ?? '?'}）`;
    const cause = f ? `${f.domain ?? '?'}/${f.code ?? '?'}${f.message ? `：${f.message}` : ''}` : `outcome=${s.outcome?.status}`;
    return `${where} ${cause}${s.diagnostic ? `；${s.diagnostic}` : ''}`;
  }
  return typeof tc.notes === 'string' && tc.notes.trim() ? tc.notes.trim() : '无 StepResult 级失败详情（见 trace）';
}

function severityFor(priority: string): DefectRow['severity'] {
  if (priority === 'P0') return 'BLOCKER';
  if (priority === 'P1') return 'MAJOR';
  return 'MINOR';
}

interface VisualFacts {
  available: boolean;
  screens: Array<{ screen_id: string; verdict: string; defects: number; must_fix: number; note: string }>;
  critic_receipt: boolean;
  measure: Map<string, { geometry: AxisStatus; detail: string }>;
}

function collectVisualFacts(projectRoot: string, feature: string): VisualFacts {
  const dir = path.join(featureDir(projectRoot, feature), 'device-testing', 'device-screenshots');
  const out: VisualFacts = { available: false, screens: [], critic_receipt: false, measure: new Map() };
  const raw = readJson<unknown>(path.join(dir, 'visual-diff.json'));
  if (raw) {
    const validated = validateVisualDiffJson(raw, projectRoot);
    if (validated.report && !validated.fatal) {
      out.available = true;
      for (const s of validated.report.screens ?? []) {
        const defects = Array.isArray((s as { defects?: unknown[] }).defects) ? (s as { defects: unknown[] }).defects : [];
        const mustFix = Array.isArray((s as { must_fix?: unknown[] }).must_fix) ? (s as { must_fix: unknown[] }).must_fix : [];
        const firstNote = defects
          .map(d => (d && typeof d === 'object' ? String((d as { note?: unknown }).note ?? '') : ''))
          .find(n => n.trim().length > 0) ?? '';
        out.screens.push({
          screen_id: String(s.screen_id ?? ''),
          verdict: String(s.verdict ?? ''),
          defects: defects.length,
          must_fix: mustFix.length,
          note: firstNote,
        });
      }
    }
  }
  out.critic_receipt = fs.existsSync(path.join(dir, 'critic-receipt.json'));
  try {
    for (const f of fs.existsSync(dir) ? fs.readdirSync(dir) : []) {
      const m = /^measure-(.+)\.json$/.exec(f);
      if (!m) continue;
      const doc = readJson<{ geometry?: { status?: string; detail?: string } }>(path.join(dir, f));
      const status = doc?.geometry?.status === 'PASS' ? 'PASS' : doc?.geometry?.status === 'FAIL' ? 'FAIL' : 'UNKNOWN';
      out.measure.set(m[1], { geometry: status, detail: doc?.geometry?.detail ?? '' });
    }
  } catch {
    /* 量测文件缺席即 UNKNOWN */
  }
  return out;
}

interface StabilityFacts {
  available: boolean;
  rows: Array<{ tc_id: string; rounds: number; consistent: number; first_divergent_step: number | null }>;
  consistent_all: boolean;
  /** codex review：每条用例同键轮数 ≥2 才有稳定性结论；单轮只是一次执行 */
  min_rounds_met: boolean;
}

function readStability(reportsDir: string): StabilityFacts {
  const doc = readJson<{ rows?: Array<{ tc_id?: string; rounds?: number; consistent?: number; first_divergent_step?: number | null }> }>(
    path.join(reportsDir, 'stability.json'),
  );
  if (!doc || !Array.isArray(doc.rows)) return { available: false, rows: [], consistent_all: false, min_rounds_met: false };
  const rows = doc.rows.map(r => ({
    tc_id: String(r.tc_id ?? ''),
    rounds: Number(r.rounds ?? 0),
    consistent: Number(r.consistent ?? 0),
    first_divergent_step: typeof r.first_divergent_step === 'number' ? r.first_divergent_step : null,
  }));
  return {
    available: true,
    rows,
    consistent_all: rows.every(r => r.rounds > 0 && r.consistent === r.rounds),
    min_rounds_met: rows.length > 0 && rows.every(r => r.rounds >= 2),
  };
}

function pct(n: number, d: number): string {
  if (d === 0) return '—';
  return `${Math.round((n / d) * 1000) / 10}%`;
}

/** 生成整份报告（纯计算，不写盘）。 */
export function generateTestReport(input: TestReportWriterInput): GeneratedTestReport {
  const { projectRoot, feature, reportsDir } = input;
  const trace: HylyreTrace | null = input.tracePath && fs.existsSync(input.tracePath) ? parseHylyreTrace(input.tracePath) : null;
  const timing = readJson<DeviceTestTimingDocument>(path.join(reportsDir, 'device-test-timing.json'));
  const runMeta = readJson<Record<string, unknown>>(path.join(reportsDir, 'device-test-run.meta.json'));
  const buildResult = readJson<Record<string, unknown>>(path.join(reportsDir, 'device-test-build.result.json'));
  const acceptance = loadAcceptanceFlowsDoc(projectRoot, feature);
  const visual = collectVisualFacts(projectRoot, feature);
  const stability = readStability(reportsDir);
  const debtLoad = loadVisualDebtEx(projectRoot, feature);
  const debt = countBlockingDebt(debtLoad.state === 'valid' ? debtLoad.doc : null);
  const debtCorrupt = debtLoad.state === 'invalid';

  const planRows = parsePlanRows(input.planMd);
  const decl = input.channelDecl;
  const gapByTc = new Map(decl.unsupported_gap.map(g => [g.tc_id.toUpperCase(), g]));
  const invalidByTc = new Map(decl.invalid_test.map(g => [g.tc_id.toUpperCase(), g]));
  const hylyreSet = new Set(decl.hylyre_tc_ids.map(id => id.toUpperCase()));
  const visualSet = new Set(decl.visual_tc_ids.map(id => id.toUpperCase()));
  const traceByTc = new Map((trace?.cases ?? []).map(c => [c.id.toUpperCase(), c]));
  const timingByTc = new Map((timing?.cases ?? []).map(c => [c.id.toUpperCase(), c]));
  const command = typeof runMeta?.command === 'string' ? runMeta.command : '';
  const weakeningFlags = ['--skip-assert-expected'].filter(f => command.includes(f));

  // AC → checkpoint screens（visual 通道 TC 与视觉缺陷的关联用例）
  const screensByAc = new Map<string, string[]>();
  for (const ac of acceptance?.criteria ?? []) {
    const cp = ac.checkpoint;
    const screens = [cp?.pre_screen, cp?.post_screen].filter((s): s is string => typeof s === 'string' && s.trim().length > 0);
    if (screens.length > 0) screensByAc.set(ac.id.toUpperCase(), screens);
  }
  const screenVerdict = new Map(visual.screens.map(s => [s.screen_id, s.verdict]));

  const exec: ExecRow[] = [];
  for (const row of planRows) {
    const gap = gapByTc.get(row.id);
    if (gap) {
      exec.push({ ...row, status: '跳过', duration: '—', note: `unsupported_gap:${gap.reason}（留分母、不算通过）`, source: 'gap' });
      continue;
    }
    if (invalidByTc.has(row.id)) {
      exec.push({ ...row, status: '阻塞', duration: '—', note: `invalid_test：${invalidByTc.get(row.id)!.why}`, source: 'invalid' });
      continue;
    }
    if (visualSet.has(row.id)) {
      const screens = [...new Set(row.acRefs.flatMap(ac => screensByAc.get(ac.toUpperCase()) ?? []))];
      const verdicts = screens.map(s => screenVerdict.get(s) ?? 'missing');
      const status: RowStatus =
        screens.length > 0 && verdicts.every(v => v === 'pass') ? '通过'
          : verdicts.some(v => v === 'fail') ? '失败' : '阻塞';
      exec.push({
        ...row, status, duration: '—',
        note: `visual 通道：屏 ${screens.join('、') || '（未声明 checkpoint 屏）'} → ${verdicts.join('/') || '无'}`,
        source: 'visual',
      });
      continue;
    }
    const tc = traceByTc.get(row.id);
    if (hylyreSet.has(row.id) || decl.hylyre_tc_ids.length === 0) {
      if (tc) {
        const t = timingByTc.get(row.id);
        const status = (['通过', '失败', '阻塞', '跳过'].includes(tc.status) ? tc.status : '阻塞') as RowStatus;
        const note = status === '失败' || status === '阻塞' ? firstFailedStepSummary(tc) : '';
        exec.push({ ...row, status, duration: t ? ms(t.duration_ms) : '0ms', note, source: 'hylyre' });
      } else {
        exec.push({ ...row, status: '跳过', duration: '—', note: trace ? '未进入本轮权威 trace（explicit skip 或未派生）' : '本轮无权威 trace', source: 'absent' });
      }
      continue;
    }
    exec.push({ ...row, status: '阻塞', duration: '—', note: `通道 ${row.channelRaw || '(空)'} 无执行事实`, source: 'invalid' });
  }

  // 缺陷
  const defects: DefectRow[] = [];
  let n = 0;
  for (const r of exec) {
    if (r.source === 'hylyre' && (r.status === '失败' || r.status === '阻塞')) {
      n += 1;
      defects.push({ id: `DEF-${String(n).padStart(3, '0')}`, cases: r.id, severity: severityFor(r.priority), description: `${r.status}：${r.note}`, status: '待修复' });
    }
  }
  const tcByScreen = new Map<string, string[]>();
  for (const row of planRows) {
    for (const ac of row.acRefs) {
      for (const s of screensByAc.get(ac.toUpperCase()) ?? []) tcByScreen.set(s, [...(tcByScreen.get(s) ?? []), row.id]);
    }
  }
  let vn = 0;
  for (const s of visual.screens) {
    if (s.verdict !== 'fail' && s.verdict !== 'warn') continue;
    vn += 1;
    const related = [...new Set(tcByScreen.get(s.screen_id) ?? [])];
    defects.push({
      id: `DEF-V${String(vn).padStart(3, '0')}`,
      cases: related.join(', '),
      severity: s.verdict === 'fail' ? 'MAJOR' : 'MINOR',
      description: `视觉 ${s.verdict}：屏 ${s.screen_id}，defects=${s.defects}，must_fix=${s.must_fix}${s.note ? `；${s.note}` : ''}`,
      status: '待修复',
    });
  }

  // 通过率
  const priorities = [...new Set(exec.map(r => r.priority))].sort();
  const thresholds: Record<string, number | null> = { P0: 100, P1: 95 };
  const rateRows: string[] = [];
  const rateOf = (rows: ExecRow[]) => {
    const total = rows.length;
    const pass = rows.filter(r => r.status === '通过').length;
    const fail = rows.filter(r => r.status === '失败').length;
    const blocked = rows.filter(r => r.status === '阻塞').length;
    const skipped = rows.filter(r => r.status === '跳过').length;
    const gaps = rows.filter(r => r.source === 'gap').length;
    return { total, pass, fail, blocked, skipped, gaps, ratio: total === 0 ? 0 : (pass / total) * 100 };
  };
  const priorityStats = new Map<string, ReturnType<typeof rateOf>>();
  for (const p of priorities) {
    const st = rateOf(exec.filter(r => r.priority === p));
    priorityStats.set(p, st);
    const th = thresholds[p] ?? null;
    const ok = th === null ? '—' : st.ratio >= th ? '✅' : '❌';
    rateRows.push(`| ${p} | ${st.total} | ${st.pass} | ${st.fail} | ${st.blocked} | ${st.skipped}${st.gaps > 0 ? `（含 gap ${st.gaps}）` : ''} | ${pct(st.pass, st.total)} | ${th === null ? '—' : p === 'P0' ? '100%' : `≥ ${th}%`} | ${ok} |`);
  }
  const all = rateOf(exec);
  rateRows.push(`| **总计** | **${all.total}** | **${all.pass}** | **${all.fail}** | **${all.blocked}** | **${all.skipped}${all.gaps > 0 ? `（含 gap ${all.gaps}）` : ''}** | **${pct(all.pass, all.total)}** | **≥ 90%** | **${all.ratio >= 90 ? '✅' : '❌'}** |`);

  // 轴
  const hylyreRows = exec.filter(r => r.source === 'hylyre');
  const functional: AxisStatus =
    !trace ? 'UNKNOWN'
      : hylyreRows.some(r => r.status === '失败' || r.status === '阻塞') || exec.some(r => r.source === 'absent' && hylyreSet.has(r.id)) || trace.outcome !== 'success'
        ? 'FAIL'
        : 'PASS';
  const stabilityAxis: AxisStatus = !stability.available || !stability.min_rounds_met ? 'UNKNOWN' : stability.consistent_all ? 'PASS' : 'FAIL';
  const p0Screens = new Set(
    (acceptance?.criteria ?? []).filter(isP0DeviceInteractive).flatMap(ac => screensByAc.get(ac.id.toUpperCase()) ?? []),
  );
  // 视觉轴只在 feature 确有视觉面（有 visual-diff.json 或 P0 checkpoint 屏）时才计入缺口
  const visualApplicable = visual.available || p0Screens.size > 0;
  let visualGeometry: AxisStatus = visualApplicable ? 'UNKNOWN' : 'NOT_APPLICABLE';
  if (!visualApplicable) {
    /* 无视觉面：三轴 NOT_APPLICABLE，不进缺口 */
  } else if (visual.measure.size > 0) {
    const statuses = [...visual.measure.values()].map(m => m.geometry);
    visualGeometry = statuses.some(s => s === 'FAIL') ? 'FAIL' : statuses.every(s => s === 'PASS') ? 'PASS' : 'UNKNOWN';
  } else if (visual.available && visual.screens.length > 0) {
    const relevant = visual.screens.filter(s => p0Screens.size === 0 || p0Screens.has(s.screen_id));
    visualGeometry = relevant.some(s => s.verdict === 'fail') ? 'FAIL'
      : relevant.length > 0 && relevant.every(s => s.verdict === 'pass') ? 'PASS' : 'UNKNOWN';
  }
  const visualContent: CheckStatus = !visualApplicable ? 'NOT_APPLICABLE' : visual.critic_receipt ? 'CHECKED' : 'UNKNOWN';
  const visualStyle: CheckStatus = !visualApplicable ? 'NOT_APPLICABLE' : visual.critic_receipt ? 'CHECKED' : 'UNKNOWN';

  const gaps: string[] = [];
  for (const g of decl.unsupported_gap) gaps.push(`${g.tc_id}[${g.channel}:${g.reason}]`);
  if (debt.open + debt.accepted > 0) gaps.push(`视觉债务 open=${debt.open}, accepted=${debt.accepted}（visual-debt.md）`);
  if (debtCorrupt) gaps.push('视觉债务账本损坏（visual-debt.json 不可解析）');
  if (visualGeometry === 'FAIL' || visualGeometry === 'UNKNOWN') gaps.push(`视觉几何 ${visualGeometry}`);
  if (visualContent === 'UNKNOWN') gaps.push('视觉内容/样式 UNKNOWN（无 provider 复核）');
  if (stabilityAxis === 'UNKNOWN') gaps.push(stability.available ? '交互稳定性 UNKNOWN（同执行键真实执行不足 2 轮，单轮不构成稳定性证据）' : '交互稳定性 UNKNOWN（无 stability.json）');
  for (const f of weakeningFlags) gaps.push(`弱化旗标 ${f}：trace「通过」仅为动作链执行完成，非验收通过`);

  const overall: OverallStatus = functional === 'FAIL' ? 'FAILED' : gaps.length > 0 || functional === 'UNKNOWN' ? 'COMPLETE_WITH_GAPS' : 'COMPLETE';
  const declared: TestReportConclusion['declared_verdict'] =
    overall === 'FAILED' ? '不达标' : overall === 'COMPLETE_WITH_GAPS' ? '有条件达标' : '达标';

  const conclusion: TestReportConclusion = {
    functional, stability: stabilityAxis, visual_geometry: visualGeometry, visual_content: visualContent,
    visual_style: visualStyle, gaps, overall, declared_verdict: declared,
  };

  // 渲染
  const rel = (p: string | null): string => (p ? path.relative(projectRoot, p).replace(/\\/g, '/') : '—');
  const traceSha = input.tracePath ? sha256File(input.tracePath) : null;
  const env = trace?.environment as Record<string, unknown> | undefined;
  const envText = [
    typeof runMeta?.device_serial === 'string' ? `device ${runMeta.device_serial}` : null,
    typeof runMeta?.device === 'string' ? `device ${runMeta.device}` : null,
    env && typeof env.hylyre_version === 'string' ? `hylyre ${env.hylyre_version}` : null,
    env && typeof env.hypium_version === 'string' ? `hypium ${env.hypium_version}` : null,
  ].filter((v): v is string => Boolean(v)).join(', ') || '（见 device-test-run.meta.json）';
  const buildAt = typeof buildResult?.timestamp === 'string' ? buildResult.timestamp.trim() : '';
  const pipeline = timing?.pipeline;
  // codex review（plan 07a41ec6 T7）：报告正文不写当前时间（否则每次重生成都换 verifier subject）——用权威 run 时间。
  const dateText =
    (typeof runMeta?.run_started_at === 'string' && runMeta.run_started_at.trim()) ||
    (typeof runMeta?.ran_at === 'string' && runMeta.ran_at.trim()) ||
    (typeof timing?.generated_at === 'string' && timing.generated_at.trim()) ||
    '（无权威 run 时间）';

  const lines: string[] = [];
  lines.push(
    TEST_REPORT_GENERATED_MARKER,
    `# 测试报告 — ${feature}`,
    '',
    `> **模块标识**: \`${feature}\``,
    `> **版本**: harness-generated ${dateText}`,
    `> **日期**: ${dateText}`,
    '> **测试执行人**: harness（机器生成；agent 观察见 testing/notes.md）',
    `> **对应测试计划**: \`${rel(resolveFeatureArtifact(projectRoot, feature, 'test-plan.md').actualPath)}\``,
    `> **权威 run**: \`${rel(input.tracePath)}\`${traceSha ? `（trace sha256 ${traceSha.slice(0, 16)}）` : ''}`,
    '',
    '> 本文件由 harness 从 trace / timing / meta / gaps / visual-diff / visual-debt / measure / stability 整份生成，重跑 harness 或 `--report-reconcile-only` 会重写；请勿手改，观察与决策写 `testing/notes.md`。',
    '',
    '---',
    '',
    '## 一、测试概览',
    '',
    '| 项目 | 内容 |',
    '|------|------|',
    `| 测试模块 | ${feature} |`,
    `| 测试日期 | ${dateText} |`,
    `| 测试环境 | ${cell(envText)} |`,
    '| 执行人 | harness（机器生成） |',
    `| 用例总数 | ${exec.length} |`,
    `| 执行用例数 | ${exec.filter(r => r.source === 'hylyre').length} |`,
    `| 跳过用例数 | ${exec.filter(r => r.status === '跳过').length} |`,
    '',
    '### 真机流水线耗时',
    '',
    '> 数据来源：device-test-timing.json（harness 在 device_test.run 成功后写入）；耗时为精确整数毫秒，`—` 表示无数据。',
    '',
    '| 阶段 | 耗时 | 说明 |',
    '|------|------|------|',
    `| 打包 (hvigor) | ${ms(pipeline?.build_ms)} | ${pipeline?.build_reused ? '复用既有 HAP' : '本轮构建'}; \`reused=${pipeline ? String(pipeline.build_reused) : 'false'}\` |`,
    `| 装机 (hdc) | ${ms(pipeline?.install_ms)} | ${pipeline?.install_reused ? '复用已装版本' : '本轮安装'}; \`reused=${pipeline ? String(pipeline.install_reused) : 'false'}\` |`,
    `| Hylyre 自动化 | ${ms(pipeline?.hylyre_run_ms)} | 含设备预启动 |`,
    `| 快照写入 (page save) | ${ms(pipeline?.page_save_ms)} | 非致命 |`,
    `| **合计（脚本统计）** | **${ms(pipeline?.total_harness_ms)}** | harness 各阶段之和（writer 为 null 时为 —） |`,
    '',
    '| 元数据 | 值 |',
    '|--------|-----|',
    `| HAP 落盘时间 (hapBuiltAt) | ${pipeline?.hap_built_at ?? '—'} |`,
    `| 本次 harness 跑 build 门禁时刻 | ${buildAt || '—'} |`,
    '',
    '---',
    '',
    '## 二、测试执行结果',
    '',
    '| 用例编号 | 用例名称 | 优先级 | 执行状态 | 耗时 | 备注 |',
    '|----------|---------|--------|---------|------|------|',
    ...exec.map(r => `| ${r.id} | ${cell(r.name)} | ${r.priority} | ${r.status} | ${r.duration} | ${cell(r.note)} |`),
    '',
  );
  if (weakeningFlags.length > 0) {
    lines.push(
      `> **弱化旗标披露**：本轮真机执行命令含 ${weakeningFlags.join('、')}——表中「通过」仅表示动作链执行完成，未验证自然语言预期/性能/视觉断言，非验收通过。`,
      '',
    );
  }
  lines.push(
    '### 稳定性（同执行键跨轮）',
    '',
  );
  if (stability.available && stability.rows.length > 0) {
    lines.push(
      '| 用例编号 | 同键轮数 | 一致轮数 | 首个分歧 step |',
      '|----------|---------|---------|--------------|',
      ...stability.rows.map(r => `| ${r.tc_id} | ${r.rounds} | ${r.consistent} | ${r.first_divergent_step ?? '—'} |`),
      '',
    );
  } else {
    lines.push('> 未生成（无 stability.json；需要 ≥2 轮同执行键的真实执行才有稳定性证据）。', '');
  }
  lines.push('---', '', '## 三、缺陷清单', '');
  if (defects.length === 0) {
    lines.push('无缺陷：所有已执行用例全部通过，视觉屏无 fail/warn。', '');
  } else {
    lines.push(
      '| 缺陷编号 | 关联用例 | 严重程度 | 描述 | 状态 |',
      '|----------|---------|---------|------|------|',
      ...defects.map(d => `| ${d.id} | ${d.cases} | ${d.severity} | ${cell(d.description)} | ${d.status} |`),
      '',
    );
  }
  const sevCount = (sev: DefectRow['severity']) => defects.filter(d => d.severity === sev).length;
  lines.push(
    '### 缺陷统计',
    '',
    '| 严重程度 | 数量 | 待修复 | 已修复 | 已关闭 | 延期处理 |',
    '|---------|------|--------|--------|--------|---------|',
    `| BLOCKER | ${sevCount('BLOCKER')} | ${sevCount('BLOCKER')} | 0 | 0 | 0 |`,
    `| MAJOR | ${sevCount('MAJOR')} | ${sevCount('MAJOR')} | 0 | 0 | 0 |`,
    `| MINOR | ${sevCount('MINOR')} | ${sevCount('MINOR')} | 0 | 0 | 0 |`,
    `| **合计** | **${defects.length}** | **${defects.length}** | **0** | **0** | **0** |`,
    '',
    '---',
    '',
    '## 四、通过率统计',
    '',
    '| 优先级 | 总用例 | 通过 | 失败 | 阻塞 | 跳过 | 通过率 | 达标阈值 | 是否达标 |',
    '|--------|--------|------|------|------|------|--------|---------|---------|',
    ...rateRows,
    '',
    '> 通过率 = 通过 / 总用例；unsupported_gap 留在总用例分母、不计入通过（P0 五数口径见 summary.json p0_coverage_integrity.structured）。',
    '',
    '---',
    '',
    '## 五、结论',
    '',
    `**测试结论**: ${declared}`,
    '',
    '**按轴结论**（确定性派生）:',
    `- 功能：${functional}（hylyre ${hylyreRows.filter(r => r.status === '通过').length}/${hylyreRows.length} 通过，失败 ${hylyreRows.filter(r => r.status === '失败').length}，阻塞 ${hylyreRows.filter(r => r.status === '阻塞').length}${trace ? `，trace.outcome=${trace.outcome}` : '，无权威 trace'}）`,
    `- 交互稳定性：${stabilityAxis}${stability.available ? `（${stability.rows.length} 条用例有同键多轮数据）` : '（无 stability.json）'}`,
    `- 视觉几何：${visualGeometry}${visual.measure.size > 0 ? `（measure 文件 ${visual.measure.size} 屏）` : visual.available ? `（visual-diff.json ${visual.screens.length} 屏：${visual.screens.map(s => `${s.screen_id}=${s.verdict}`).join('、')}）` : '（无 visual-diff.json）'}`,
    `- 视觉内容：${visualContent}`,
    `- 视觉样式：${visualStyle}`,
    `- 已知缺口：${gaps.length === 0 ? '无' : `${gaps.length} 项`}`,
    ...gaps.map(g => `  - ${g}`),
    `- 总体：${overall}`,
    '',
    '**判定依据**:',
    ...priorities.map(p => {
      const st = priorityStats.get(p)!;
      const th = thresholds[p] ?? null;
      return `- ${p} 通过率: ${pct(st.pass, st.total)}（${th === null ? '无阈值' : p === 'P0' ? '阈值 100%' : `阈值 ≥ ${th}%`}）`;
    }),
    `- 总体通过率: ${pct(all.pass, all.total)}（阈值 ≥ 90%）`,
    `- BLOCKER 缺陷: ${sevCount('BLOCKER')} 个`,
    debt.open + debt.accepted > 0
      ? `- 视觉债务 ${debt.open + debt.accepted} 条未清偿（open=${debt.open}, accepted=${debt.accepted}；SSOT=visual-debt.json / summary.quality_axes），功能达标与视觉验真是两根轴`
      : '- 视觉债务 0 条',
    '',
    '**下一步建议**:',
    overall === 'FAILED'
      ? '- 修复失败/阻塞用例（见缺陷清单）后重跑 testing harness；未执行的 hylyre 用例补跑。'
      : overall === 'COMPLETE_WITH_GAPS'
        ? '- 功能完成可推进；已知缺口按条目在需求/spec 登记并披露，视觉缺口不阻止功能完成但阻断 release_readiness。'
        : '- 功能模块验收完成。',
    '',
  );
  return { content: lines.join('\n'), conclusion, trace_path: input.tracePath };
}

export interface WriteGeneratedTestReportResult {
  written: boolean;
  path: string;
  legacy_moved_to?: string;
  conclusion?: TestReportConclusion;
  reason?: string;
}

/** 写入 canonical test-report.md；首次覆盖手写报告时把旧文件迁到 testing/notes.legacy-report.md 留档。 */
export function writeGeneratedTestReport(input: TestReportWriterInput): WriteGeneratedTestReportResult {
  const target = resolveFeatureArtifact(input.projectRoot, input.feature, 'test-report.md').canonicalPath;
  try {
    const generated = generateTestReport(input);
    let legacyMovedTo: string | undefined;
    if (fs.existsSync(target)) {
      const existing = fs.readFileSync(input.projectRoot ? target : target, 'utf-8');
      if (!existing.includes(TEST_REPORT_GENERATED_MARKER)) {
        const notesDir = path.join(featureDir(input.projectRoot, input.feature), 'testing');
        fs.mkdirSync(notesDir, { recursive: true });
        legacyMovedTo = path.join(notesDir, 'notes.legacy-report.md');
        fs.writeFileSync(legacyMovedTo, `<!-- 由 harness 迁移：以下是机器生成报告接管前的手写 test-report.md（plan 07a41ec6 T5） -->\n\n${existing}`, 'utf-8');
      }
    }
    fs.mkdirSync(path.dirname(target), { recursive: true });
    fs.writeFileSync(target, generated.content, 'utf-8');
    return { written: true, path: target, ...(legacyMovedTo ? { legacy_moved_to: legacyMovedTo } : {}), conclusion: generated.conclusion };
  } catch (e) {
    return { written: false, path: target, reason: (e as Error).message };
  }
}
